/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddServiceDrawer: typeof import('./src/components/AddServiceDrawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceList: typeof import('./src/components/ServiceList.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    WebView: typeof import('./src/components/WebView.vue')['default']
    WebViewLoad: typeof import('./src/components/WebViewLoad.vue')['default']
  }
}
