/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddServiceDrawer: typeof import('./src/components/AddServiceDrawer.vue')['default']
    ContextMenuPopover: typeof import('./src/components/ContextMenuPopover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceList: typeof import('./src/components/ServiceList.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    WebView: typeof import('./src/components/WebView.vue')['default']
    WebviewEnable: typeof import('./src/components/WebviewEnable.vue')['default']
    WebViewError: typeof import('./src/components/WebViewError.vue')['default']
    WebViewLoad: typeof import('./src/components/WebViewLoad.vue')['default']
  }
}
